name: tests

on: [push]

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-go@v6
              with:
                go-version: "1.23.4"
            - run: go mod download
    
    unit-tests:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-go@v6
              with:
                go-version: "1.23.4"
            - run: |
                go test -coverprofile=unit-coverage.txt -covermode=atomic -coverpkg=./cmd/...,./internal/...,./pkg/... ...
            - uses: codecov/codecov-action@v5
              with:
                files: unit-coverage.txt
                token: ${{ secrets.CODECOV_TOKEN }}